trigger: none

pool: my agent pool

variables: 
- name: svc
  value: 'todo-service-connection'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: '$(svc)'
    backendAzureRmStorageAccountName: 'todostorageaccount001'
    backendAzureRmContainerName: 'todocontainer'
    backendAzureRmKey: 'terraform.tfstate'